// ========================================
// Adip Lowkey - 100+ Quotes Collection
// Tambah/ubah quotes di bawah ini sesuai keinginan
// ========================================

const quotes = [
    // Quotes produksi musik
    "Musik adalah bahasa yang dipahami oleh setiap jiwa.",
    "Dari nol, sekarang di sini. Prosesnya yang membuatku bertahan.",
    "Setiap beat punya cerita. Setiap remix punya perjalanan.",
    "Belajar dari nol bukan malu, tapi kebanggaan.",
    "RMX bukan cuma remix, tapi identitas yang kukenakan.",
    "Bass turun, jiwa naik.",
    "Satu karya, ribuan jam belajar.",
    "Lowkey tapi tetap ada di setiap ketukan.",
    "Tidak ada yang instan, termasuk musik yang enak didengar.",
    "Duduk sendiri di depan FL Studio, menciptakan dunia sendiri.",
    "Dari Bekasi, untuk dunia.",
    "Remix adalah seni memberi jiwa baru pada lagu.",
    "Tidak perlu studio mahal untuk membuat musik berkualitas.",
    "Setiap drop adalah ekspresi dari perasaan yang tidak bisa diucapkan.",
    "Musik elektronik adalah canvas, FL Studio adalah kuasku.",
    "Jatuh bangun belajar musik, tapi tidak pernah menyerah.",
    "Simpel tapi penuh energi, itulah ciri khasku.",
    "Hidup itu seperti mixing, harus balance setiap elemennya.",
    "Dari yang awam tentang audio, kini menciptakan audio sendiri.",
    "Semangat itu ada di setiap ketukan kick drum.",
    "Masih belajar, masih berkembang, dan masih di jalan.",
    "Musik tidak mengenal batasan, karena perasaan tidak punya batas.",
    "Ketukan bass yang paling dalam, datang dari jiwa yang paling tulus.",
    "Setiap lagu yang kuremix punya kenangan yang berbeda.",
    "Tidak mudah, tapi tidak mustahil.",
    "Belajar otodidak, tapi hasilnya tetap original.",
    "Musik adalah jalan pulang bagi setiap perasaan yang tersesat.",
    "Dari kelas XI SMK, menemukan passion sejati.",
    "Tiap hari belajar, tiap hari berkembang.",
    "FL Studio Mobile awalnya bikin uninstall, kini jadi ladang kreativitas.",
    "Ketukan simpel yang diciptakan dengan tulus, lebih berharga dari yang rumit tapi palsu.",
    "Setiap genre punya cerita, setiap BPM punya emosi.",
    "Berkarya dari kamar kecil, bermimpi ke panggung besar.",
    "Musik tidak pernah salah, yang ada hanya eksplorasi.",
    "ADIP RMX untuk yang lama, Adip Lowkey untuk yang kini.",
    "Proses dari nol mengajarkan arti kesabaran sejati.",
    "Mencoba, gagal, coba lagi, berhasil. Pola hidupku.",
    "Remix bukan tentang menghancurkan, tapi memperbarui.",
    "Jadilah suara yang kamu ingin dengar di dunia.",
    "BPM tidak bisa bohong, karena angka tidak punya emosi palsu.",
    "Setiap transisi adalah peluang untuk membuat sesuatu yang baru.",
    "Duduk diam tidak akan menghasilkan beat.",
    "Sound design adalah seni membentuk suara tak terlihat.",
    "Terus berkarya meski yang menonton sedikit.",
    "Yang penting konsisten, bukan sempurna.",
    "Sukses itu bukan tujuan, tapi proses belajar tanpa henti.",
    "Musikku mungkin tidak sempurna, tapi selalu jujur.",
    "Tidak ada yang namanya terlambat untuk mulai belajar musik.",
    "Ketika kata-kata gagal, biarkan musik yang berbicara.",
    "Semua produser besar juga pernah dari nol.",
    "Hidup seperti sequencer, semua punya timing yang tepat.",
    "Dari Depok, untuk semua yang mendengar.",
    "Jangan takut untuk bereksperimen dengan suara baru.",
    "Setiap EQ cut adalah keputusan artistik.",
    "Musik elektronik adalah bentuk lain dari matematika yang bisa dirasakan.",
    "Komunitas RMXFAMS adalah keluarga kedua.",
    "Dari penasaran, jadi passion, jadi profesi.",
    "Satu track bisa mengubah mood, bayangkan ribuan.",
    "Keep it lowkey, but make it hit hard.",
    "Tidak pernah terlalu tua untuk remix lagu favorit.",
    "Ketukan yang konsisten lebih baik dari yang kompleks tapi berantakan.",
    "Musik adalah investasi waktu yang tidak pernah rugi.",
    "Dari X7Teen, 1NE, RMXFAMS, hingga BMR. Tiap komunitas mengajarkan sesuatu.",
    "Fokus pada proses, hasil akan mengikuti.",
    "Semua yang terlihat mudah, pernah terasa sulit di awal.",
    "Keterbatasan equipment bukan alasan untuk berhenti berkarya.",
    "Musikku adalah diary yang bisa didengar.",
    "Percaya pada prosesnya, jangan hanya pada hasilnya.",
    "Jika hatimu berdetak, kamu sudah punya ritme.",
    "Tidak ada formula sempurna, hanya ekspresi yang tulus.",
    "Belajar dari nol membuatku menghargai setiap progres.",
    "Setiap plug-in punya karakter, setiap VST punya cerita.",
    "Musik adalah satu-satunya hal yang tetap ada saat semua pergi.",
    "Dari yang tidak tahu apa-apa, kini jadi yang mengajari orang lain.",
    "ADIP RMX lahir dari rasa penasaran, Adip Lowkey lahir dari kedewasaan.",
    "Riset suara sehari-hari adalah pekerjaan produser.",
    "Jangan bandingkan chapter 1mu dengan chapter 20 orang lain.",
    "Kualitas datang dari kuantitas yang konsisten.",
    "Tidak ada yang salah dengan belajar dari tutorial YouTube.",
    "Setiap master track adalah bab baru dalam perjalanan.",
    "Musik adalah bentuk kebebasan yang tidak bisa diambil.",
    "Duduk di depan DAW selama berjam-jam adalah meditasi modern.",
    "Gagal mixing adalah pelajaran mixing.",
    "Dari penasaran di 2023, jadi passion di 2024, jadi cinta di 2025.",
    "Lowkey does not mean low quality.",
    "Ketika dunia berisik, buatlah musik yang tenang.",
    "Produser adalah arsitek dunia suara.",
    "Tidak perlu jadi yang terbaik, cukup jadi yang lebih baik dari kemarin.",
    "Setiap kick drum adalah langkah ke depan.",
    "Musik adalah warisan yang tidak bisa dihapus.",
    "Mulai dari kecil, bermimpi besar, bekerja keras.",
    "Tidak ada batasan usia untuk membuat musik yang bagus.",
    "Ketika dunia tidur, produser bekerja.",
    "Berkarya untuk diri sendiri dulu, audiens akan mengikuti.",
    "Dari yang uninstall FL Studio, kini jadi produksi berkualitas.",
    "Semangat itu gratis, tapi hasilnya berharga.",
    "Mengubah nada menjadi perasaan adalah sihir sejati.",
    "Tidak pernah puas, selalu ada yang bisa diperbaiki.",
    "Musik adalah jembatan antara perasaan dan kata-kata.",
    "Tiap marga, tiap tim, tiap label adalah chapter hidup.",
    "Keep learning, keep remixing, keep growing.",
    "Tidak ada yang namanya terlalu simpel jika dibuat dengan hati.",
    "Soundcloud ke Spotify, perjalanan yang panjang tapi layak.",
    "Dari Bekasi lahir, di Depok berkarya, untuk dunia bermusik.",
    "Sejuta karya dimulai dari satu beat yang berani.",
    "Tidak semua yang glitch harus diperbaiki, kadang itu adalah ciri khas.",
    "Produser yang hebat adalah pendengar yang hebat.",
    "Masih di awal perjalanan, tapi serius menjalani setiap langkah.",
    "Musikku adalah jawaban atas pertanyaan yang tidak terucap.",
    "Dari nol tanpa basic, kini punya fondasi yang kokoh.",
    "Setiap chord progression adalah jalan yang belum pernah dilalui.",
    "Lowkey, but the music speaks volumes.",
    "Hidup ini seperti project file, selalu bisa di-save dan dilanjutkan.",
    "Dynotic Collective, Malindo Music Group, SC Music Group. Bersama mereka, musikku menjangkau lebih luas.",
    "Tidak ada yang lebih memuaskan daripada melihat progres sendiri.",
    "Keep the bass low and the dreams high."
];

// Function to get random quote
function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { quotes, getRandomQuote };
}
